version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webcafe-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI}
    networks:
      - webcafe-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webcafe-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - webcafe-network

networks:
  webcafe-network:
    driver: bridge
